// <auto-generated />
using System;
using BazadlaL.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BazadlaL.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210723150628_initmysql")]
    partial class initmysql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BazadlaL.API.Models.DewormingDog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<int>("FdogId");

                    b.Property<string>("Preparat");

                    b.HasKey("Id");

                    b.HasIndex("FdogId");

                    b.ToTable("DewormingDog");
                });

            modelBuilder.Entity("BazadlaL.API.Models.DewormingPuppy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Preparat");

                    b.Property<int>("PuppyId");

                    b.HasKey("Id");

                    b.HasIndex("PuppyId");

                    b.ToTable("DewormingPuppy");
                });

            modelBuilder.Entity("BazadlaL.API.Models.Fdog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataUrodzenia");

                    b.Property<string>("DlugoscSiersci");

                    b.Property<string>("Imie");

                    b.Property<string>("Masc");

                    b.Property<string>("Plec");

                    b.Property<string>("Rasa");

                    b.Property<bool>("Rodowod");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fdog");
                });

            modelBuilder.Entity("BazadlaL.API.Models.Puppy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataUrodzenia");

                    b.Property<string>("DlugoscSiersci");

                    b.Property<string>("Imie");

                    b.Property<string>("Masc");

                    b.Property<int>("MatkaId");

                    b.Property<string>("Plec");

                    b.Property<string>("Rasa");

                    b.Property<bool>("Rodowod");

                    b.HasKey("Id");

                    b.HasIndex("MatkaId");

                    b.ToTable("Puppy");
                });

            modelBuilder.Entity("BazadlaL.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BazadlaL.API.Models.VaccinationDog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<int>("FdogId");

                    b.Property<string>("Nazwa");

                    b.Property<string>("Seria");

                    b.Property<DateTime>("Waznosc");

                    b.HasKey("Id");

                    b.HasIndex("FdogId");

                    b.ToTable("VaccinationDog");
                });

            modelBuilder.Entity("BazadlaL.API.Models.VaccinationPuppy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Nazwa");

                    b.Property<int>("PuppyId");

                    b.Property<string>("Seria");

                    b.Property<DateTime>("Waznosc");

                    b.HasKey("Id");

                    b.HasIndex("PuppyId");

                    b.ToTable("VaccinationPuppy");
                });

            modelBuilder.Entity("BazadlaL.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("BazadlaL.API.Models.DewormingDog", b =>
                {
                    b.HasOne("BazadlaL.API.Models.Fdog", "fdog")
                        .WithMany("DewormingDog")
                        .HasForeignKey("FdogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BazadlaL.API.Models.DewormingPuppy", b =>
                {
                    b.HasOne("BazadlaL.API.Models.Puppy", "puppy")
                        .WithMany("DewormingPuppy")
                        .HasForeignKey("PuppyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BazadlaL.API.Models.Fdog", b =>
                {
                    b.HasOne("BazadlaL.API.Models.User", "User")
                        .WithMany("Fdogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BazadlaL.API.Models.Puppy", b =>
                {
                    b.HasOne("BazadlaL.API.Models.Fdog", "Matka")
                        .WithMany("Puppies")
                        .HasForeignKey("MatkaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BazadlaL.API.Models.VaccinationDog", b =>
                {
                    b.HasOne("BazadlaL.API.Models.Fdog", "fdog")
                        .WithMany("VaccinationDog")
                        .HasForeignKey("FdogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BazadlaL.API.Models.VaccinationPuppy", b =>
                {
                    b.HasOne("BazadlaL.API.Models.Puppy", "puppy")
                        .WithMany("VaccinationPuppy")
                        .HasForeignKey("PuppyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
